version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: camp-chat-backend:local
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:rw
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    # Use a healthcheck that matches your app, optional
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
